[build]
  # Build command
  command = "npm install --force && ng build --prod"
  # Directory where your built project is located
   publish = "www"

# Redirects can be added here if needed
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
