[build]
  # Build command
  command = "npm install --legacy-peer-deps && ng build"
   publish = "social-media/social-media/www"

# Redirects can be added here if needed
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
